from datetime import date

from werkzeug.security import generate_password_hash

from .extensions import db
from .models import Promotion, Restaurant, User


RESTAURANTS = [
    {
        "name": "Restaurante Mare Alta",
        "segment": "Restaurante",
        "neighborhood": "Gonzaga",
        "address": "Av. Ana Costa, 013 - Gonzaga, Santos",
        "phone": "(13) 99901-0013",
        "instagram": "@marealta013",
        "image_url": "https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1200&q=80",
        "logo_url": "https://placehold.co/220x220/06234F/FFFFFF.png?text=MA",
        "promotion_book_image_url": "https://placehold.co/900x520/06234F/FFFFFF.png?text=Ganhe+sobremesa",
        "latitude": -23.9686,
        "longitude": -46.3322,
        "distance_meters": 850,
        "accepts_in_person": True,
        "accepts_delivery": False,
        "pet_friendly": True,
        "kids_area": False,
        "promotion": {
            "title": "Sobremesa gratis",
            "description": "Ganhe uma sobremesa na compra de um prato principal.",
            "rules": "Valido de segunda a quinta. Informe o livrinho antes de pedir.",
        },
    },
    {
        "name": "Cantina do Porto",
        "segment": "Italiano",
        "neighborhood": "Ponta da Praia",
        "address": "Rua Trabulsi, 240 - Ponta da Praia, Santos",
        "phone": "(13) 99902-0013",
        "instagram": "@cantinadoporto",
        "image_url": "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80",
        "logo_url": "https://placehold.co/220x220/B82F2F/FFFFFF.png?text=CP",
        "promotion_book_image_url": "https://placehold.co/900x520/B82F2F/FFFFFF.png?text=2o+prato+50%25",
        "latitude": -23.9879,
        "longitude": -46.2987,
        "distance_meters": 1400,
        "accepts_in_person": True,
        "accepts_delivery": True,
        "pet_friendly": False,
        "kids_area": True,
        "promotion": {
            "title": "Segundo prato com 50%",
            "description": "Na compra de uma massa, a segunda sai com 50% de desconto.",
            "rules": "Desconto aplicado no prato de menor valor.",
        },
    },
    {
        "name": "Sushi 013",
        "segment": "Japones",
        "neighborhood": "Boqueirao",
        "address": "Av. Conselheiro Nebias, 613 - Boqueirao, Santos",
        "phone": "(13) 99903-0013",
        "instagram": "@sushi013",
        "image_url": "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=1200&q=80",
        "logo_url": "https://placehold.co/220x220/111827/FFFFFF.png?text=S13",
        "promotion_book_image_url": "https://placehold.co/900x520/111827/FFFFFF.png?text=Combo+especial",
        "latitude": -23.9654,
        "longitude": -46.3208,
        "distance_meters": 980,
        "accepts_in_person": True,
        "accepts_delivery": True,
        "pet_friendly": False,
        "kids_area": False,
        "promotion": {
            "title": "Combo especial do livrinho",
            "description": "Ganhe 8 hots na compra de um combinado especial.",
            "rules": "Valido para consumo no salao ou retirada.",
        },
    },
    {
        "name": "Burger Gonzaga",
        "segment": "Hamburgueria",
        "neighborhood": "Gonzaga",
        "address": "Rua Tolentino Filgueiras, 88 - Gonzaga, Santos",
        "phone": "(13) 99904-0013",
        "instagram": "@burgergonzaga",
        "image_url": "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1200&q=80",
        "logo_url": "https://placehold.co/220x220/F2B705/111111.png?text=BG",
        "promotion_book_image_url": "https://placehold.co/900x520/F2B705/111111.png?text=Batata+gratis",
        "latitude": -23.9702,
        "longitude": -46.3362,
        "distance_meters": 620,
        "accepts_in_person": True,
        "accepts_delivery": True,
        "pet_friendly": True,
        "kids_area": False,
        "promotion": {
            "title": "Batata da casa gratis",
            "description": "Ganhe uma porcao de batata na compra de dois burgers.",
            "rules": "Nao cumulativo com outras promocoes.",
        },
    },
    {
        "name": "Cafe da Praia",
        "segment": "Cafeteria",
        "neighborhood": "Aparecida",
        "address": "Av. Bartolomeu de Gusmao, 120 - Aparecida, Santos",
        "phone": "(13) 99905-0013",
        "instagram": "@cafedapraia013",
        "image_url": "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=1200&q=80",
        "logo_url": "https://placehold.co/220x220/7C4A26/FFFFFF.png?text=CPR",
        "promotion_book_image_url": "https://placehold.co/900x520/7C4A26/FFFFFF.png?text=Cafe+em+dobro",
        "latitude": -23.9768,
        "longitude": -46.3091,
        "distance_meters": 1100,
        "accepts_in_person": True,
        "accepts_delivery": False,
        "pet_friendly": True,
        "kids_area": False,
        "promotion": {
            "title": "Cafe em dobro",
            "description": "Compre um cappuccino grande e ganhe outro igual.",
            "rules": "Valido ate as 18h.",
        },
    },
    {
        "name": "Pizzaria Canal 3",
        "segment": "Pizzaria",
        "neighborhood": "Embare",
        "address": "Rua Oswaldo Cruz, 303 - Embare, Santos",
        "phone": "(13) 99906-0013",
        "instagram": "@pizzariacanal3",
        "image_url": "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=1200&q=80",
        "logo_url": "https://placehold.co/220x220/D9480F/FFFFFF.png?text=C3",
        "promotion_book_image_url": "https://placehold.co/900x520/D9480F/FFFFFF.png?text=Borda+gratis",
        "latitude": -23.9669,
        "longitude": -46.3136,
        "distance_meters": 1250,
        "accepts_in_person": False,
        "accepts_delivery": True,
        "pet_friendly": False,
        "kids_area": False,
        "promotion": {
            "title": "Borda recheada gratis",
            "description": "Ganhe borda recheada em pizzas grandes no delivery.",
            "rules": "Valido para pedidos por telefone.",
        },
    },
    {
        "name": "Acai do Boqueirao",
        "segment": "Acai",
        "neighborhood": "Boqueirao",
        "address": "Rua Azevedo Sodre, 45 - Boqueirao, Santos",
        "phone": "(13) 99907-0013",
        "instagram": "@acaidoboqueirao",
        "image_url": "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?auto=format&fit=crop&w=1200&q=80",
        "logo_url": "https://placehold.co/220x220/6D28D9/FFFFFF.png?text=AC",
        "promotion_book_image_url": "https://placehold.co/900x520/6D28D9/FFFFFF.png?text=300ml+gratis",
        "latitude": -23.9632,
        "longitude": -46.3274,
        "distance_meters": 760,
        "accepts_in_person": True,
        "accepts_delivery": True,
        "pet_friendly": False,
        "kids_area": True,
        "promotion": {
            "title": "Upgrade de tamanho",
            "description": "Pague 500ml e leve 700ml no acai tradicional.",
            "rules": "Valido uma vez por livrinho.",
        },
    },
    {
        "name": "Espaco Veg Santos",
        "segment": "Vegano",
        "neighborhood": "Vila Rica",
        "address": "Rua Bahia, 91 - Vila Rica, Santos",
        "phone": "(13) 99908-0013",
        "instagram": "@espacovegsantos",
        "image_url": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1200&q=80",
        "logo_url": "https://placehold.co/220x220/248A3D/FFFFFF.png?text=EV",
        "promotion_book_image_url": "https://placehold.co/900x520/248A3D/FFFFFF.png?text=Suco+gratis",
        "latitude": -23.9549,
        "longitude": -46.3342,
        "distance_meters": 1650,
        "accepts_in_person": True,
        "accepts_delivery": True,
        "pet_friendly": True,
        "kids_area": False,
        "promotion": {
            "title": "Suco natural gratis",
            "description": "Ganhe um suco na compra de um prato executivo vegano.",
            "rules": "Valido no almoco.",
        },
    },
    {
        "name": "Churrasco da Vila",
        "segment": "Churrascaria",
        "neighborhood": "Vila Belmiro",
        "address": "Rua Princesa Isabel, 1912 - Vila Belmiro, Santos",
        "phone": "(13) 99909-0013",
        "instagram": "@churrascodavila",
        "image_url": "https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?auto=format&fit=crop&w=1200&q=80",
        "logo_url": "https://placehold.co/220x220/991B1B/FFFFFF.png?text=CV",
        "promotion_book_image_url": "https://placehold.co/900x520/991B1B/FFFFFF.png?text=Bebida+gratis",
        "latitude": -23.9518,
        "longitude": -46.3458,
        "distance_meters": 2400,
        "accepts_in_person": True,
        "accepts_delivery": False,
        "pet_friendly": False,
        "kids_area": True,
        "promotion": {
            "title": "Bebida da casa gratis",
            "description": "Ganhe uma bebida na compra de um prato executivo.",
            "rules": "Valido apenas no salao.",
        },
    },
    {
        "name": "Doceria Orla",
        "segment": "Doceria",
        "neighborhood": "Aparecida",
        "address": "Av. Pedro Lessa, 77 - Aparecida, Santos",
        "phone": "(13) 99910-0013",
        "instagram": "@doceriaorla",
        "image_url": "https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=1200&q=80",
        "logo_url": "https://placehold.co/220x220/BE185D/FFFFFF.png?text=DO",
        "promotion_book_image_url": "https://placehold.co/900x520/BE185D/FFFFFF.png?text=Doce+extra",
        "latitude": -23.9761,
        "longitude": -46.3055,
        "distance_meters": 1320,
        "accepts_in_person": True,
        "accepts_delivery": True,
        "pet_friendly": False,
        "kids_area": False,
        "promotion": {
            "title": "Doce extra",
            "description": "Na compra de 6 doces, ganhe mais 2 unidades.",
            "rules": "Valido para doces selecionados.",
        },
    },
]


def seed_database():
    user = User.query.filter_by(email="gustavo@email.com").first()
    if not user:
        user = User(
            name="Gustavo",
            email="gustavo@email.com",
            phone=None,
            birth_date=date(2005, 6, 10),
            auth_provider="manual",
            password_hash=generate_password_hash("123456"),
        )
        db.session.add(user)

    for item in RESTAURANTS:
        restaurant = Restaurant.query.filter_by(name=item["name"]).first()
        if not restaurant:
            promotion_data = item["promotion"]
            restaurant_data = {key: value for key, value in item.items() if key != "promotion"}
            restaurant = Restaurant(**restaurant_data)
            restaurant.promotions.append(
                Promotion(
                    title=promotion_data["title"],
                    description=promotion_data["description"],
                    image_url=restaurant.promotion_book_image_url,
                    rules=promotion_data["rules"],
                )
            )
            db.session.add(restaurant)

    db.session.commit()
